[package]
name = "sc-macros"
version = "0.1.0"
edition = "2021"
[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0.96", features = ["full"] }
static_assertions = "1.1.0"
deluxe="0.5.0"